- hosts: masters
  become: true
  tasks:
  - name: Install the prerequisites (wget, JDK8)
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - wget
      - java-1.8.0-openjdk.x86_64

  - name: Download and add the package manager repository for the Client Master
    get_url:
      url: https://downloads.cloudbees.com/cloudbees-core/traditional/client-master/rolling/rpm/cloudbees-core-cm.repo
      dest: /etc/yum.repos.d/cloudbees-core-cm.repo

  - name: Import the GPG key of the repository
    rpm_key:
      state: present
      key: https://downloads.cloudbees.com/jenkins-operations-center/rolling/rpm/cloudbees.com.key

  - name: Install Cloudbees Core Client Master
    yum:
      name: cloudbees-core-cm
      state: latest

  - name: Enable and start Cloudbees Core Client Master service
    service:
      name: cloudbees-core-cm
      enabled: true
      state: started